navn = input("Skriv dit navn her: ")
alder = int(input("Skriv din alder her: "))
højde = float(input("Skriv din højde her: "))
print("Goddag hr./fru: ", navn)
print("Du er ", alder, " år gammel og er", højde, "meter høj.")